export const ADD_PICKUP_DATE="ADD_PICKUP_DATE"
export const ADD_DROPOFF_DATE="ADD_DROPOFF_DATE"
export const ADD_VEHICLE_DETAILS="ADD_VEHICLE_DETAILS"

export const VEHICLE_BOOK_REQUEST="VEHICLE_BOOK_REQUEST";
export const VEHICLE_BOOK_SUCCESS="VEHICLE_BOOK_SUCCESS";
export const VEHICLE_BOOK_FAIL="VEHICLE_BOOK_FAIL"